### ISSUE TITLE
VercelにQin-ToDoをデプロイする

### ISSUE THREAD

**Issue by mo-ri-regen** [mo-ri-regen/qin-todo-frontend#138]
環境変数は[ここ](https://github.com/mo-ri-regen/qin-todo-frontend/wiki/%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0#firebase%E9%96%A2%E9%80%A3)を参照

**Comment by mo-ri-regen** [comment]
@takasaki376 @yoko-at-home 

環境変数をセットしてデプロイしたらエラーが出ました。
https://vercel.com/mo-ri-regen/qin-todo-frontend/6B7WsRDBfQ1WuCpr1tx33mFHUmhr
は見えますかね?

設定した環境変数が間違っているのでしょうか。それともソースの変更が必要なのでしょうか。

catch文をつけたら解決しそうな気がしますが。https://scrapbox.io/tasuwo/Node.js_%E3%81%A7_UnhandledPromiseRejectionWarning_%E3%81%8C%E3%81%A7%E3%81%9F%E3%81%A8%E3%81%8D

## エラー内容

- cookieの設定が必要?

```


(node:666) UnhandledPromiseRejectionWarning: Error: Invalid next-firebase-auth options: The "cookies.keys" setting must be set if "cookies.signed" is true.
--
21:19:18.651 | at b (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:9873)
21:19:18.651 | at Object.init (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:17650)
21:19:18.651 | at init (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:27305)
21:19:18.651 | at initAuth (/vercel/path0/.next/server/chunks/452.js:33:59)
21:19:18.652 | at Object.5770 (/vercel/path0/.next/server/pages/_app.js:374:25)
21:19:18.652 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
21:19:18.652 | at __webpack_exec__ (/vercel/path0/.next/server/pages/_app.js:449:52)
21:19:18.652 | at /vercel/path0/.next/server/pages/_app.js:450:83
21:19:18.653 | at /vercel/path0/.next/server/pages/_app.js:450:47
21:19:18.653 | (Use `node --trace-warnings ...` to show where the warning was created)
```

- asyncのtry文にcatch文がないエラー

```
(node:666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

上記エラーとも関係してそうかもしれません

```
(node:666) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
--
21:19:18.680 |  
21:19:18.680 | > Build error occurred
21:19:18.684 | Error: Invalid next-firebase-auth options: The "cookies.keys" setting must be set if "cookies.signed" is true.
21:19:18.685 | at b (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:9873)
21:19:18.685 | at Object.init (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:17650)
21:19:18.685 | at init (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:27305)
21:19:18.685 | at initAuth (/vercel/path0/.next/server/chunks/452.js:33:59)
21:19:18.686 | at Object.5770 (/vercel/path0/.next/server/pages/_app.js:374:25)
21:19:18.686 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
21:19:18.686 | at __webpack_exec__ (/vercel/path0/.next/server/pages/_app.js:449:52)
21:19:18.686 | at /vercel/path0/.next/server/pages/_app.js:450:83
21:19:18.687 | at Function.__webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:108:21)
21:19:18.687 | at /vercel/path0/.next/server/pages/_app.js:450:47 {
21:19:18.687 | type: 'Error'
21:19:18.687 | }
21:19:18.771 | error Command failed with exit code 1.
21:19:18.774 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:19:18.788 | Error: Command "yarn run build" exited with 1
```

**Comment by takasaki376** [comment]
とりあえず、下記の行が出ているので、ソースコードの修正はできないと思います。
```
21:19:18.651 | at b (/vercel/path0/node_modules/next-firebase-auth/build/index.node.js:2:9873)
```

原因は、firebaseの設定値だと思います。

**Comment by mo-ri-regen** [comment]
見直してみます

**Comment by takasaki376** [comment]
wikiの記載に漏れがあれば、追記していきましょう。

**Comment by mo-ri-regen** [comment]
@takasaki376 @yoko-at-home 
デプロイできました。
環境変数の設定値が足りていなかったみたいです🙇🏼‍♂️
よろしければcloseしてください


https://qin-todo-frontend-qsqfirc2i-mo-ri-regen.vercel.app/

>COOKIE_SECRET_CURRENT=[任意の値]
COOKIE_SECRET_PREVIOUS=[任意の値]

と書かれていたので適当に設定しました

**Comment by mo-ri-regen** [comment]
どっちのボタンでもいいんですけど、「Googleでログイン」押したとき反応しますか?
firebaseの設定が必要でしょうか?
https://gyazo.com/768b00943dffc56389f19526a1202578

**Comment by takasaki376** [comment]
サインアップはこちら。figmaでもアカウント作成画面へのリンクはなかった気がします
https://qin-todo-frontend-qsqfirc2i-mo-ri-regen.vercel.app/auth/signup

google ログインの設定はこちらです。
https://blog.katsubemakito.net/firebase/firebase-authentication-google-web1

**Comment by mo-ri-regen** [comment]
@takasaki376 さん
ログインできること確認しました。

※設定の問題かもしれないですがアカウント作成後、認証のメールは届かないです。

よろしければcloseしてください。

**Comment by takasaki376** [comment]
確認しましたので、クローズします。

認証メールはフロント側にメール送信ロジックが必要なのですが、QinMemoにはロジックがなかったので実装していません。届かないのが正解です。
